version: '3.7'
services:
  url-shortener-server:
    restart: always
    container_name: url-shortener-server
    env_file:
      - .env
    environment: 
      - NODE_ENV=production
    build:
      context: ./
    image: url-shortener-server

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/server/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/server/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 